import { Button, Text } from '@nextui-org/react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import React from 'react';
import Navbar from '../components/Navbar';

const HomeScreen = () => {
  return (
    <div className="h-screen">
      <Head>
        <title>Finesse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <div
          style={{
            objectFit: 'cover',
            width: '100%',
            height: '100%',
            position: 'fixed',
            opacity: 0.3,
            zIndex: 0,
            transform: ' translate(-50%, -50%) rotate(-45deg)'
          }}
        >
          {[...Array(100)].map(() => {
            return (
              <div className="flex flex-row overflow-visible">
                {[...Array(100)].map(() => (
                  <Text size="$2xl"> FINESSE </Text>
                ))}
              </div>
            );
          })}
        </div>

        <div
          className="relative z-10 top-40 text-center px-24"
          style={{ left: '50%', transform: 'translateX(-50%)' }}
        >
          <Image
            className="mx-auto"
            src={'/finesse-logo-yellow.png'}
            width={757}
            height={159}
            alt="Finesse logo"
          />
          <Text h1 className="mt-12">
            A DeFi-powered ecosystem for fans to get exclusive access to their
            favorite songs and music artists.
          </Text>
          <Link href="/exchange">
            <Button className="mx-auto mt-12" color="secondary" size="lg">
              <Text weight="extrabold" size="$2xl">
                Launch App
              </Text>
            </Button>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default HomeScreen;
